config/routes.rb
Rails.application.routes.draw do

  resources :site_proceeds

  resources :site_funds

  resources :provider_funds
  resources :client_receipts
  resources :proceeds
  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
  devise_for :sites, :controllers => {registrations: 'registrations'}
   resources :provider_alerts
   resources :entries
   resources :payments
   resources :counseling_sessions
   resources :sites
   resources :providers do
     resources :reviews
  end
   resources :funds do
     resources :payments
  end
   root 'home#index'
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   post 'funds_submit' => 'funds#funds_submit'
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   get 'funds/confirm' => 'funds#confirm', via: [:get, :post]
   get 'counseling_sess/provider_joined/:id' => 'counseling_sessions#provider_joined', as: :provider_joined
   post 'entr/entry_submit' => 'entries#entry_submit', as: :entry_submit
   post 'entr/entry_get' => 'entries#entry_get', as: :entry_get
   get 'provs/session_options' => 'providers#session_options', as: :session_options
   get 'prov_alerts/get_alert_count' => 'provider_alerts#get_alert_count', as: :get_alert_count
   post 'entr/end_session' => 'entries#end_session', as: :end_session
   post 'counseling_sess/session_ended' => 'counseling_sessions#session_ended', as: :session_ended
   get 'counseling_sess/charges_settled' => 'counseling_sessions#charges_settled', as: :charges_settled
   get 'counseling_sess/client_session_ended' => 'counseling_sessions#client_session_ended', as: :client_session_ended
   get 'client_rec/session_transcript' => 'client_receipts#session_transcript', as: :session_transcript
# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/site_fund.rb
class SiteFund < ActiveRecord::Base
  belongs_to :site
end

app/controllers/site_funds_controller.rb
class SiteFundsController < ApplicationController
  before_action :set_site_fund, only: [:show, :edit, :update, :destroy]

  # GET /site_funds
  # GET /site_funds.json
  def index
    @site_funds = SiteFund.all
  end

  # GET /site_funds/1
  # GET /site_funds/1.json
  def show
  end

  # GET /site_funds/new
  def new
    @site_fund = SiteFund.new
  end

  # GET /site_funds/1/edit
  def edit
  end

  # POST /site_funds
  # POST /site_funds.json
  def create
    @site_fund = SiteFund.new(site_fund_params)

    respond_to do |format|
      if @site_fund.save
        format.html { redirect_to @site_fund, notice: 'Site fund was successfully created.' }
        format.json { render :show, status: :created, location: @site_fund }
      else
        format.html { render :new }
        format.json { render json: @site_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_funds/1
  # PATCH/PUT /site_funds/1.json
  def update
    respond_to do |format|
      if @site_fund.update(site_fund_params)
        format.html { redirect_to @site_fund, notice: 'Site fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_fund }
      else
        format.html { render :edit }
        format.json { render json: @site_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_funds/1
  # DELETE /site_funds/1.json
  def destroy
    @site_fund.destroy
    respond_to do |format|
      format.html { redirect_to site_funds_url, notice: 'Site fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_fund
      @site_fund = SiteFund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_fund_params
      params.require(:site_fund).permit(:avail_amount)
    end
end

app/helpers/site_funds_helper.rb
module SiteFundsHelper
end

app/views/site_funds/_form.html.erb
<%= form_for(@site_fund) do |f| %>
  <% if @site_fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_fund.errors.count, "error") %> prohibited this site_fund from being saved:</h2>

      <ul>
      <% @site_fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avail_amount %><br>
    <%= f.text_field :avail_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_funds/edit.html.erb
<h1>Editing site_fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_fund %> |
<%= link_to 'Back', site_funds_path %>

app/views/site_funds/index.html.erb
<h1>Listing site_funds</h1>

<table>
  <thead>
    <tr>
      <th>Avail amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_funds.each do |site_fund| %>
      <tr>
        <td><%= site_fund.avail_amount %></td>
        <td><%= link_to 'Show', site_fund %></td>
        <td><%= link_to 'Edit', edit_site_fund_path(site_fund) %></td>
        <td><%= link_to 'Destroy', site_fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site fund', new_site_fund_path %>

app/views/site_funds/new.html.erb
<h1>New site_fund</h1>

<%= render 'form' %>

<%= link_to 'Back', site_funds_path %>

app/views/site_funds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avail amount:</strong>
  <%= @site_fund.avail_amount %>
</p>

<%= link_to 'Edit', edit_site_fund_path(@site_fund) %> |
<%= link_to 'Back', site_funds_path %>