config/routes.rb
Rails.application.routes.draw do

  resources :site_proceeds

  resources :site_funds

  resources :provider_funds
  resources :client_receipts
  resources :proceeds
  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
  devise_for :sites, :controllers => {registrations: 'registrations'}
   resources :provider_alerts
   resources :entries
   resources :payments
   resources :counseling_sessions
   resources :sites
   resources :providers do
     resources :reviews
  end
   resources :funds do
     resources :payments
  end
   root 'home#index'
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   post 'funds_submit' => 'funds#funds_submit'
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   get 'funds/confirm' => 'funds#confirm', via: [:get, :post]
   get 'counseling_sess/provider_joined/:id' => 'counseling_sessions#provider_joined', as: :provider_joined
   post 'entr/entry_submit' => 'entries#entry_submit', as: :entry_submit
   post 'entr/entry_get' => 'entries#entry_get', as: :entry_get
   get 'provs/session_options' => 'providers#session_options', as: :session_options
   get 'prov_alerts/get_alert_count' => 'provider_alerts#get_alert_count', as: :get_alert_count
   post 'entr/end_session' => 'entries#end_session', as: :end_session
   post 'counseling_sess/session_ended' => 'counseling_sessions#session_ended', as: :session_ended
   get 'counseling_sess/charges_settled' => 'counseling_sessions#charges_settled', as: :charges_settled
   get 'counseling_sess/client_session_ended' => 'counseling_sessions#client_session_ended', as: :client_session_ended
   get 'client_rec/session_transcript' => 'client_receipts#session_transcript', as: :session_transcript
# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/provider_alert.rb
class ProviderAlert < ActiveRecord::Base
  belongs_to :provider
  belongs_to :client
  belongs_to :counseling_session
  
  def mark_as_read
    self.answered = true
    save!
  end
end

app/controllers/provider_alerts_controller.rb
class ProviderAlertsController < ApplicationController

  # GET /provider_alerts
  # GET /provider_alerts.json
  def index
    @provider_alerts = ProviderAlert.where(provider_id: current_provider.id).order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end

  # GET /provider_alerts/1
  # GET /provider_alerts/1.json
  def show
    @provider_alert = ProviderAlert.find_by(id: params[:id], provider: current_provider)
    if @provider_alert == nil
      redirect_to provider_alerts_path
    else
      @provider_alert.mark_as_read
    end
  end
  
  respond_to :json
  def get_alert_count
    @provider = current_provider
    if (@provider != nil)
      @provider_alerts = ProviderAlert.where(provider: current_provider, answered: false)
      render json: @provider_alerts.count
    end
  end

  # GET /provider_alerts/new
  def new
    @provider_alert = ProviderAlert.new
  end

  

  # POST /provider_alerts
  # POST /provider_alerts.json
  def create
    @provider_alert = ProviderAlert.new(provider_alert_params)

    respond_to do |format|
      if @provider_alert.save
        format.html { redirect_to @provider_alert, notice: 'Provider alert was successfully created.' }
        format.json { render :show, status: :created, location: @provider_alert }
      else
        format.html { render :new }
        format.json { render json: @provider_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provider_alerts/1
  # PATCH/PUT /provider_alerts/1.json
  def update
    respond_to do |format|
      if @provider_alert.update(provider_alert_params)
        format.html { redirect_to @provider_alert, notice: 'Provider alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider_alert }
      else
        format.html { render :edit }
        format.json { render json: @provider_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provider_alerts/1
  # DELETE /provider_alerts/1.json
  def destroy
    @provider_alert = ProviderAlert.find(params[:id])
    @provider_alert.destroy
    respond_to do |format|
      format.html { redirect_to provider_alerts_url, notice: 'Provider alert deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def provider_alert_params
      params.require(:provider_alert).permit(:provider_id_id, :client_id_id, :alert_text)
    end
end

app/helpers/provider_alerts_helper.rb
module ProviderAlertsHelper
end

app/views/provider_alerts/_form.html.erb
<%= form_for(@provider_alert) do |f| %>
  <% if @provider_alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider_alert.errors.count, "error") %> prohibited this provider_alert from being saved:</h2>

      <ul>
      <% @provider_alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider_id_id %><br>
    <%= f.text_field :provider_id_id %>
  </div>
  <div class="field">
    <%= f.label :client_id_id %><br>
    <%= f.text_field :client_id_id %>
  </div>
  <div class="field">
    <%= f.label :alert_text %><br>
    <%= f.text_area :alert_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provider_alerts/index.html.erb
<div class="mainContent">
	<div class="signUpBlockDiv">
		<h1 class="label">Provider Alerts</h1>
	</div>
	<div class="mainContentPrepare">
		<div class="alertBox">
			<div class="alertContent">

				<% @provider_alerts.each_with_index do |alert, index| %>
				<% if index % 2 == 0 %>
					<% if alert.answered %>
					<div class='talkBoxRowStyle1 label'>
					<%else%>
					<div class='talkBoxRowStyle1 boldLabel'>
					<%end%>					
				<%else%>
					<% if alert.answered %>
					<div class='talkBoxRowStyle2 label'>
					<%else%>
					<div class='talkBoxRowStyle2 boldLabel'>
					<%end%>
				<%end%>		
					<%= link_to alert do%>		
					<div class="client_by_client_narration">
						<%= alert.client.first_name + " " + alert.client.last_name %>
					</div>		
					<div class="client_by_client_text">
						<%= alert.alert_subject[0..50] %><% if alert.alert_subject.length > 50 %>...<%end%>
					</div>
					<div class="client_by_client_date">
						<%= alert.created_at.to_formatted_s(:short_inbox) %>
					</div>
					<div class="client_by_client_delete">
						<%= link_to "Delete", provider_alert_path(alert), {data: { confirm: "Delete Alert?" },  method: :delete, class: "submit override" } %>

					</div>
					<%end%>			
					
				</div>
				<%end%>
				<%= will_paginate %>
			</div>
		</div>
	</div>
</div>

app/views/provider_alerts/show.html.erb
<div class="mainContent">
	<div class="signUpBlockDiv">
		<h1 class="label">Alert From <%= @provider_alert.client.first_name %> <%= @provider_alert.client.last_name%></h1>
	</div>
	<div class="mainContentPrepare">
		<div class="alertBox">
			<div class="alertSubject"><%= @provider_alert.alert_subject %>.</div>
			<div class="alertText"><%= @provider_alert.alert_text %></div>
			<% if @provider_alert.counseling_session.session_type == 1 %>
			<div class="accept">
				<% if @provider_alert.alert_type == 1 %>
					<%= link_to new_counseling_session_path(provider_id: current_provider.id, session_type: 1, id: @provider_alert.counseling_session.id) do %>
					<div class="gridLinkSchedBox gridLinkBox">
					Join Chat Session
					</div>
					<%end%>
				<% elsif @provider_alert.alert_type == 2 %>
					<%= link_to end_session_path(counseling_session_id: @provider_alert.counseling_session.id), method: :post do %>
					<div class="gridLinkSchedBox gridLinkBox">
					Submit Charges
					</div>
					<%end%>
				<%end%> 
			</div>
			<%end%>
		</div>
	</div>
	<%= link_to 'Delete Alert', provider_alert_path, method: :delete, data: {confirm: "Delete This Alert?"} %>
</div>