config/routes.rb
Rails.application.routes.draw do

  resources :site_proceeds

  resources :site_funds

  resources :provider_funds
  resources :client_receipts
  resources :proceeds
  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
  devise_for :sites, :controllers => {registrations: 'registrations'}
   resources :provider_alerts
   resources :entries
   resources :payments
   resources :counseling_sessions
   resources :sites
   resources :providers do
     resources :reviews
  end
   resources :funds do
     resources :payments
  end
   root 'home#index'
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   post 'funds_submit' => 'funds#funds_submit'
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   get 'funds/confirm' => 'funds#confirm', via: [:get, :post]
   get 'counseling_sess/provider_joined/:id' => 'counseling_sessions#provider_joined', as: :provider_joined
   post 'entr/entry_submit' => 'entries#entry_submit', as: :entry_submit
   post 'entr/entry_get' => 'entries#entry_get', as: :entry_get
   get 'provs/session_options' => 'providers#session_options', as: :session_options
   get 'prov_alerts/get_alert_count' => 'provider_alerts#get_alert_count', as: :get_alert_count
   post 'entr/end_session' => 'entries#end_session', as: :end_session
   post 'counseling_sess/session_ended' => 'counseling_sessions#session_ended', as: :session_ended
   get 'counseling_sess/charges_settled' => 'counseling_sessions#charges_settled', as: :charges_settled
   get 'counseling_sess/client_session_ended' => 'counseling_sessions#client_session_ended', as: :client_session_ended
   get 'client_rec/session_transcript' => 'client_receipts#session_transcript', as: :session_transcript
# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/site_proceed.rb
class SiteProceed < ActiveRecord::Base
  belongs_to :client
  belongs_to :provider
  belongs_to :counseling_session
  belongs_to :site
end

app/controllers/site_proceeds_controller.rb
class SiteProceedsController < ApplicationController
  before_action :set_site_proceed, only: [:show, :edit, :update, :destroy]

  # GET /site_proceeds
  # GET /site_proceeds.json
  def index
    @site_proceeds = SiteProceed.all
  end

  # GET /site_proceeds/1
  # GET /site_proceeds/1.json
  def show
  end

  # GET /site_proceeds/new
  def new
    @site_proceed = SiteProceed.new
  end

  # GET /site_proceeds/1/edit
  def edit
  end

  # POST /site_proceeds
  # POST /site_proceeds.json
  def create
    @site_proceed = SiteProceed.new(site_proceed_params)

    respond_to do |format|
      if @site_proceed.save
        format.html { redirect_to @site_proceed, notice: 'Site proceed was successfully created.' }
        format.json { render :show, status: :created, location: @site_proceed }
      else
        format.html { render :new }
        format.json { render json: @site_proceed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_proceeds/1
  # PATCH/PUT /site_proceeds/1.json
  def update
    respond_to do |format|
      if @site_proceed.update(site_proceed_params)
        format.html { redirect_to @site_proceed, notice: 'Site proceed was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_proceed }
      else
        format.html { render :edit }
        format.json { render json: @site_proceed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_proceeds/1
  # DELETE /site_proceeds/1.json
  def destroy
    @site_proceed.destroy
    respond_to do |format|
      format.html { redirect_to site_proceeds_url, notice: 'Site proceed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_proceed
      @site_proceed = SiteProceed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_proceed_params
      params.require(:site_proceed).permit(:client_id, :provider_id, :counseling_session_id, :total_session_amount, :provider_amount, :commission_amount, :commission_percentage)
    end
end

app/helpers/site_proceeds_helper.rb
module SiteProceedsHelper
end

app/views/site_proceeds/_form.html.erb
<%= form_for(@site_proceed) do |f| %>
  <% if @site_proceed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_proceed.errors.count, "error") %> prohibited this site_proceed from being saved:</h2>

      <ul>
      <% @site_proceed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :provider_id %><br>
    <%= f.text_field :provider_id %>
  </div>
  <div class="field">
    <%= f.label :counseling_session_id %><br>
    <%= f.text_field :counseling_session_id %>
  </div>
  <div class="field">
    <%= f.label :total_session_amount %><br>
    <%= f.text_field :total_session_amount %>
  </div>
  <div class="field">
    <%= f.label :provider_amount %><br>
    <%= f.text_field :provider_amount %>
  </div>
  <div class="field">
    <%= f.label :commission_amount %><br>
    <%= f.text_field :commission_amount %>
  </div>
  <div class="field">
    <%= f.label :commission_percentage %><br>
    <%= f.text_field :commission_percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_proceeds/edit.html.erb
<h1>Editing site_proceed</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_proceed %> |
<%= link_to 'Back', site_proceeds_path %>

app/views/site_proceeds/index.html.erb
<h1>Listing site_proceeds</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Provider</th>
      <th>Counseling session</th>
      <th>Total session amount</th>
      <th>Provider amount</th>
      <th>Commission amount</th>
      <th>Commission percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_proceeds.each do |site_proceed| %>
      <tr>
        <td><%= site_proceed.client %></td>
        <td><%= site_proceed.provider %></td>
        <td><%= site_proceed.counseling_session %></td>
        <td><%= site_proceed.total_session_amount %></td>
        <td><%= site_proceed.provider_amount %></td>
        <td><%= site_proceed.commission_amount %></td>
        <td><%= site_proceed.commission_percentage %></td>
        <td><%= link_to 'Show', site_proceed %></td>
        <td><%= link_to 'Edit', edit_site_proceed_path(site_proceed) %></td>
        <td><%= link_to 'Destroy', site_proceed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site proceed', new_site_proceed_path %>

app/views/site_proceeds/new.html.erb
<h1>New site_proceed</h1>

<%= render 'form' %>

<%= link_to 'Back', site_proceeds_path %>

app/views/site_proceeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @site_proceed.client %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @site_proceed.provider %>
</p>

<p>
  <strong>Counseling session:</strong>
  <%= @site_proceed.counseling_session %>
</p>

<p>
  <strong>Total session amount:</strong>
  <%= @site_proceed.total_session_amount %>
</p>

<p>
  <strong>Provider amount:</strong>
  <%= @site_proceed.provider_amount %>
</p>

<p>
  <strong>Commission amount:</strong>
  <%= @site_proceed.commission_amount %>
</p>

<p>
  <strong>Commission percentage:</strong>
  <%= @site_proceed.commission_percentage %>
</p>

<%= link_to 'Edit', edit_site_proceed_path(@site_proceed) %> |
<%= link_to 'Back', site_proceeds_path %>