config/routes.rb
Rails.application.routes.draw do

  resources :site_proceeds

  resources :site_funds

  resources :provider_funds
  resources :client_receipts
  resources :proceeds
  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
  devise_for :sites, :controllers => {registrations: 'registrations'}
   resources :provider_alerts
   resources :entries
   resources :payments
   resources :counseling_sessions
   resources :sites
   resources :providers do
     resources :reviews
  end
   resources :funds do
     resources :payments
  end
   root 'home#index'
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   post 'funds_submit' => 'funds#funds_submit'
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   get 'funds/confirm' => 'funds#confirm', via: [:get, :post]
   get 'counseling_sess/provider_joined/:id' => 'counseling_sessions#provider_joined', as: :provider_joined
   post 'entr/entry_submit' => 'entries#entry_submit', as: :entry_submit
   post 'entr/entry_get' => 'entries#entry_get', as: :entry_get
   get 'provs/session_options' => 'providers#session_options', as: :session_options
   get 'prov_alerts/get_alert_count' => 'provider_alerts#get_alert_count', as: :get_alert_count
   post 'entr/end_session' => 'entries#end_session', as: :end_session
   post 'counseling_sess/session_ended' => 'counseling_sessions#session_ended', as: :session_ended
   get 'counseling_sess/charges_settled' => 'counseling_sessions#charges_settled', as: :charges_settled
   get 'counseling_sess/client_session_ended' => 'counseling_sessions#client_session_ended', as: :client_session_ended
   get 'client_rec/session_transcript' => 'client_receipts#session_transcript', as: :session_transcript
# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/views/layouts/js/_coun_sess_callback.html.erb
<script type='text/javascript'>	
		function providerJoinedResponse(responseTxt, statusTxt, xhr)
		{
			if (statusTxt == "success")
			{
				if (responseTxt == "true")
				{
					$("#session_wait").css("visibility", "hidden");
					$("#session_start").css("visibility", "visible");
				}
			}
			
		}
			(function() {
				$(document).ready(function() {
					setInterval((function() {
						$("#session_timer").load('<%= provider_joined_path(@counseling_session) %>', providerJoinedResponse);
					}), 3000);
				});

			}).call(this);
		</script>

app/views/layouts/js/_digi_stripe.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
Stripe.setPublishableKey('<%= ENV['PUBLISHABLE_KEY'] %>');
var selector;
	function switchSelector(control)
	{
		selector = control.id == "c2" ? 0 : 1;
		if (selector == 1)
		 {
		 	document.getElementById('use_previous').style.display = 'none';
		 	document.getElementById('use_new').style.display= 'block';
		 }
		 else
		 {
		 	document.getElementById('use_previous').style.display = 'block';
		 	document.getElementById('use_new').style.display= 'none';
		 }
	}
$(document).ready(function() { 
	
	function addInputNames() {
		$(".card_number").attr("name", "card_number")
		$(".card_code").attr("name", "card_code")
		$(".card_month").attr("name", "card_month")
		$(".card_year").attr("name", "card_year")
	}

	function removeInputNames() {
		$(".card_number").removeAttr("name")
		$(".card_code").removeAttr("name")
		$(".card_month").removeAttr("name")
		$(".card_year").removeAttr("name")
	}
	function submit(form) {
		if (selector == null || selector == 1)
		{
			removeInputNames();
			$(form['commit']).attr("disabled", "disabled")
			Stripe.createToken(
				{
					number : $('#card_number').val(),
					cvc : $('#card_code').val(),
					exp_month : $('#card_month').val(),
					exp_year : $('#card_year').val()
				}, function(status, response) {
					if (response.error) {
						$(form['commit']).removeAttr("disabled")
						$(".payment-errors").html(response.error.message);
			
						addInputNames();
					} 
					else {
						var token = response['id'];	
						$("#fund_stripe_card_token").val(token);
			
						form.submit();
					}
				});
			return false;
		}
		else
		{
			$(form['commit']).attr("disabled", "disabled")
			var cValue = document.getElementById("#ticket_category_clone").options[e.selectedIndex].value;
        	Stripe.createToken(
				{
					//TODO: rearrange these params
					card: cValue
				}, function(status, response) {
					if (response.error) {
						$(form['commit']).removeAttr("disabled")
						$(".payment-errors").html(response.error.message);
			
						addInputNames();
					} 
					else {
						var token = response['id'];	
						$("#fund_stripe_card_token").val(token);
			
						form.submit();
					}
				});
			return false;
		}
	}

	jQuery.validator.addMethod("cardNumber", Stripe.validateCardNumber, "Please enter a valid card number");
	jQuery.validator.addMethod("cardCVC", Stripe.validateCVC, "Please enter a valid security code");
	jQuery.validator.addMethod("cardExpiry", function() {
		return Stripe.validateExpiry($(".card_month").val(), $(".card_year").val())
		}, "Please enter a valid expiration");
	
	
	<% if !@fund.new_record? %>
		$(".edit_fund").validate({
			submitHandler : submit,
			rules : {			
			}
			
			});		
	<%end%>
	
<% if @fund.new_record? %>
jQuery.validator.addMethod("cardNumber", Stripe.validateCardNumber, "Please enter a valid card number");
	jQuery.validator.addMethod("cardCVC", Stripe.validateCVC, "Please enter a valid security code");
	jQuery.validator.addMethod("cardExpiry", function() {
		return Stripe.validateExpiry($(".card_month").val(), $(".card_year").val())
		}, "Please enter a valid expiration");
		
	$(".new_fund").validate({
		
		submitHandler : submit,
		rules : {
			"card_code" : {
				cardCVC : true,
				required : true
			},
			"card_number" : {
				cardNumber : true,
				required : true
			},
			"card_year" : "cardExpiry" 
		}
		
	});
	
	addInputNames();
	
	<%end%>
	 selector = document.getElementById('c1').checked ? 1 : 2;
	 if (selector == 1)
	 {
	 	document.getElementById('use_previous').style.display = 'none';
	 	document.getElementById('use_new').style.display= 'block';
	 }
	 else if (selector == 0)
	 {
	 	document.getElementById('use_previous').style.display = 'block';
	 	document.getElementById('use_new').style.display= 'none';
	 }
	 else
	 {
	 	document.getElementById('use_previous').style.display = 'none';
	 	document.getElementById('use_new').style.display= 'none';
	 }
});

</script>

app/views/layouts/js/_entries_callback.html.erb
<script type="text/javascript">
	(function() {
		$(document).ready(function() {
			if ($(".entry_text").val() == "" || $(".entry_text").val() == null) {
				$(".submission").prop("disabled", true);
			} else
				$(".submission").prop("disabled", false);
			setInterval((function() {
						getMessage();
					}), 3000);
		});

	}).call(this);

	function textChanged(e) {
		if (e.keyCode != 13) {
			if ($("textarea[name='entry_text']").val() == "" || $("textarea[name='entry_text']").val() == null) {
				$(".submission").prop("disabled", true);
			} else {
				$(".submission").prop("disabled", false);
			}
		} else {
			$(".submission").click();
			
		}
	}
	
	function getMessage()
	{
		var dataParams = {
							'client_id': '<%= @counseling_session.client_id %>',
						   'counseling_session_id': '<%= @counseling_session.id %>',
						   'provider_id': '<%= @counseling_session.provider_id %>',						   	
						};
		$.ajax({
			url: '<%= entry_get_path %>',
			type: 'POST',
			data: dataParams,
			error: function() { handleGetError() }
		});
	}
	
	function sendMessage()
	{
		if ($("#entry_text").val() == '\n')
		{
			$("#entry_text").val("");
			return;
		}
		$("textarea[name='entry_text']").prop("disabled", true);
		$(".submission").prop("disabled", true);
		var dataParams = { 'entry_text': $("#entry_text").val(), 
						   'client_id': '<%= @counseling_session.client_id %>',
						   'counseling_session_id': '<%= @counseling_session.id %>',
						   'provider_id': '<%= @counseling_session.provider_id %>',
						   <% if current_client %>
						   'entry_by_client': 'true',
						   'entry_by_provider': 'false'
						   <%else%>
						   'entry_by_client': 'false',
						   'entry_by_provider': 'true' 
						   <%end%>
						 };
		
				$.ajax({
    				url: '<%= entry_submit_path %>',
    				type: 'POST',
    				data: dataParams,
    				error: function(){ handleError() }
  				});
		$("textarea[name='entry_text']").val("");
		
	}
	
	function scroll()
	{
		$('.talkContent').animate({scrollTop: $('.talkContent')[0].scrollHeight}, 500);
	}
	
	function handleError()
	{
		$("#error-messages").text("There was an error sending the message. Please try again.");
		$("textarea[name='entry_text']").prop("disabled", false);
		$(".submission").prop("disabled", true);
	}
	function handleGetError()
	
	{
		$("#error-messages").text("There was an error receiving a message. Please notify the other user to resend.");
		<% if @counseling_session.session_ended %>
		
		<%end%>
	}
	
	function showAlertCount(responseTxt)
{
	if (parseInt(responseTxt) == 0)
	{
		$(".alert_indicator").css("background-color", "transparent");
		$(".alert_indicator").css("color", "transparent");
		$(".alert_indicator").css("box-shadow", "none");
		$(".alert_indicator").css("text-shadow", "none");
	}
	else
	{
		$(".alert_indicator").css("background-color", "#FF0000");
		$(".alert_indicator").css("border-radius", "15px");
		$(".alert_indicator").css("color", "#FFFFFF");
		$(".alert_indicator").css("padding-left", "3px");
		$(".alert_indicator").css("padding-right", "4px");
		$(".alert_indicator").css("box-shadow", "1px 1px 8px rgba(33,33,33,0.9)");
		$(".alert_indicator").css("text-shadow", "1px 8px 8px rgba(0,0,0,0.5)");
	}
}

</script>

app/views/layouts/js/_poll_alerts.html.erb
<script type="text/javascript">
//(function() {
				//$(document).ready(function() {
					//setInterval((function() {
						//$(".alert_indicator").load('<%= get_alert_count_path %>', showAlertCount);
					//}), 3000);
				//});

			//}).call(this);
			
function showAlertCount(responseTxt)
{
	if (parseInt(responseTxt) == 0)
	{
		$(".alert_indicator").css("background-color", "transparent");
		$(".alert_indicator").css("color", "transparent");
		$(".alert_indicator").css("box-shadow", "none");
		$(".alert_indicator").css("text-shadow", "none");
	}
	else
	{
		$(".alert_indicator").css("background-color", "#FF0000");
		$(".alert_indicator").css("border-radius", "15px");
		$(".alert_indicator").css("color", "#FFFFFF");
		$(".alert_indicator").css("padding-left", "3px");
		$(".alert_indicator").css("padding-right", "4px");
		$(".alert_indicator").css("box-shadow", "1px 1px 8px rgba(33,33,33,0.9)");
		$(".alert_indicator").css("text-shadow", "1px 8px 8px rgba(0,0,0,0.5)");
	}
}

<% if controller.action_name == 'end_session'%>
function switchTimeModify(s)
{
	if (s.checked)
	{
		$("#alt_time_div").css("display", "block");
	}
	else
	{
		$("#alt_time_div").css("display", "none");
	}
}			
<%end%>
</script>